version: '3.8'

services:
  laravel-app:
    image: suryaaaulia/laravel_image:latest
    restart: always
    ports:
      - '8000:8000'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db_mysql
      - DB_PORT=3306
      - DB_DATABASE=myskin
      - DB_USERNAME=root
      - DB_PASSWORD=
      - REDIS_HOST=redis
      - REDIS_PASSWORD=""
    depends_on:
      - db_mysql
      - redis

  react-app:
    image: suryaaaulia/react_image:latest
    container_name: react_app
    restart: always
    ports:
      - '5173:5173'
    environment:
      - REACT_APP_API_URL=http://laravel-app:8000
    depends_on:
      - laravel-app

  flask-app:
    image: suryaaaulia/flask_image:latest
    container_name: flask_app
    restart: always
    ports:
      - '7000:7000'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8001:80'
    environment:
      - PMA_HOST=db_mysql
    depends_on:
      - db_mysql

  db_mysql:
    image: mysql:8.0
    container_name: db_mysql
    ports:
      - '3306:3306'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: myskin
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=root

volumes:
  db-data: ~

